services:

  api1: &api
    build:
      context: .
      dockerfile: dockerfile
    hostname: api1
    environment:
      - DEFAULT_PAYMENT=http://payment-processor-default:8080
      - FALLBACK_PAYMENT=http://payment-processor-fallback:8080
      - DB_URL=http://db-api:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "50MB"
  api2:
    <<: *api
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "50MB"
  db-api:
    <<: *api
    hostname: db-api
    environment:
      - IS_DB_SERVICE=true
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "50MB"
  redirect:
    <<: *api
    hostname: redirect
    depends_on:
      - api1
      - api2
    networks:
      - backend
      - payment-processor
    environment:
      - LISTEN_ADDR=0.0.0.0:9999
      - TARGET_ADDRS=api1:8080,api2:8080
    ports:
      - "9999:9999"
    command: ["/redirect"]

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true