services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"

  api1: &api
    build:
      context: .
      dockerfile: dockerfile
    hostname: api1
    environment:
      - DEFAULT_PAYMENT=http://payment-processor-default:8080
      - FALLBACK_PAYMENT=http://payment-processor-fallback:8080
      - DB_URL=http://db-api:9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "30MB"
  api2:
    <<: *api
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "30MB"
  db-api:
    <<: *api
    hostname: db-api
    environment:
      - IS_DB_SERVICE=true
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true