services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1: &api
    build:
      context: .
      dockerfile: ./dockerfile
    hostname: api1
    environment:
      - DEFAULT_PAYMENT=http://host.docker.internal:8001
      - FALLBACK_PAYMENT=http://host.docker.internal:8002
      - SIBLING_SERVICE_URL=http://api2:9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "50MB"
  api2:
    <<: *api
    hostname: api2
    environment:
      - DEFAULT_PAYMENT=http://host.docker.internal:8002
      - FALLBACK_PAYMENT=http://host.docker.internal:8001
      - SIBLING_SERVICE_URL=http://api1:9999

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true